---
- include_tasks:        '../tasks/dependencies.yml'
- include_tasks:                '../tasks/install_packages.yml'
- include_tasks:                '../tasks/known_hosts.yml'
- include_tasks:                '../tasks/create_files.yml'
- include_tasks:                '../tasks/lines_in_files.yml'
- include_tasks:                '../tasks/shell_commands.yml'
  when:                         lines_in_files_result.changed
