---
- include_tasks:                'tasks/common/install_packages.yml'
- include_tasks:                'tasks/common/known_hosts.yml'
- include_tasks:                'tasks/common/create_files.yml'
- include_tasks:                'tasks/common/lines_in_files.yml'
- include_tasks:                'tasks/common/shell_commands.yml'
  when:                         lines_in_files_result.changed
