---
- include:                      '../tasks/install_packages.yml'
- include:                      '../tasks/create_files.yml'
- include:                      '../tasks/lines_in_files.yml'
- include:                      '../tasks/shell_commands.yml'
  when:                         lines_in_files_result.changed
